### ISSUE TITLE
项目无法使用代理功能吧

### ISSUE THREAD

**Issue by Tony-1240645041** [lyytaw/tawdemo-socks5-c#1]
看了你的1.0版本代码，就是一般的socket通信吧，能实现TCP的全局代理功能吗？

**Comment by lyytaw** [comment]
能的，里面有对socks5协议的解析，不过最好不要真实使用，因为还是会被墙的。而且由于未使用epoll/kqueue之类的，性能不怎么样，仅可以当做学习参考

**Comment by lyytaw** [comment]
不好意思，刚发现原来v1.0分支的README没有，刚刚补充了一下
